
#
# Based on:
# - https://github.com/kraj/meta-clang/blob/master/.github/workflows
# - https://github.com/garmin/meta-lts-collab/tree/dunfell/.github/workflows
name: yocto-sdk-container

on:
  workflow_dispatch:
    inputs:
          branch:
            description: 'The Yocto branch that is intended to be built'
            default: 'scarthgap'
            required: false
            type: string
          runner:
            description: 'The runner to execute this workfow with'
            default: 'linux'
            required: false
            type: string
          # run-tests:
          #   description: 'If true, runs the testimage tests after building'
          #   default: false
          #   required: false
          #   type: boolean
          save-cache:
            description: 'Saves the download and sstate cache after the build finishes'
            default: true
            required: false
            type: boolean
          use-cache:
            description: 'Restores the download and sstate cache before building'
            default: true
            required: false
            type: boolean

  schedule:
    - cron: " 0 3 * * SUN"

jobs:
  build:
    name: Yocto Erlang SDK build container
    runs-on: [ubuntu-latest]
    timeout-minutes: 720
    strategy:
      matrix:
        platform: [genericx86-64]
        clib: [glibc]
    steps:
      - name: Clone erlang-build-linux
        uses: actions/checkout@v6
        with:
          path: ${{ github.workspace }}/erlang-build-linux

      - name: Restore downloads and sstate
        id: cache-restore
        if: ${{ inputs.use-cache }}
        uses: actions/cache/restore@v5
        with:
          path: |
            ${{ github.workspace }}//data-work/yocto/downloads
            ${{ github.workspace }}//data-work/yocto/sstate-cache
          key: downloads-and-sstate-${{ inputs.branch }}-${{ runner.name }}
          restore-keys: |
            downloads-and-sstate-${{ inputs.branch }}

      - name: Setup and run bitbake
        run: |
          sudo apt-get update
          sudo apt install pipx
          pipx install kas

          cd ${{ github.workspace }}/erlang-build-linux
          
          export YOCTO_DIR=${{ github.workspace }}/data-work/yocto
          export KAS=kas-container

          echo dir create $YOCTO_DIR
          mkdir -v -p ${YOCTO_DIR}

          echo yocto dir
          ls -l ${YOCTO_DIR}

          echo workspace
          ls -l ${{ github.workspace }}

          echo here
          pwd
          ls -l

          make build-${{ matrix.platform }}-${{ matrix.clib }}

          ls -l $YOCTO_DIR/builds/scarthgap-erlang-build/


      # - name: Export SDK OCI containers

      # - name: Prepare results
      #   run: |
      #     cd yoe
      #     /bin/bash -c ". ./envsetup.sh qemuarm64 && resulttool report build/tmp/log/oeqa"

      # - name: Clean shared state
      #   run: |
      #     cd yoe
      #     /bin/bash -c ". ./envsetup.sh qemuarm64 && sstate-cache-management.py -d --remove-orphans -y "

      - name: Save downloads and sstate
        if: ${{ inputs.save-cache }}
        uses: actions/cache/save@v5
        with:
          path: |
            ${{ github.workspace }}//data-work/yocto/downloads
            ${{ github.workspace }}//data-work/yocto/sstate-cache
          key: downloads-and-sstate-${{ inputs.branch }}-${{ runner.name }}